### ISSUE TITLE
[DONATION] BinaryHeartbeat

### ISSUE THREAD

**Issue by MJFlynn** [uea-machine-learning/tsml_repo#21] opened 2019-10-22 10:15 UTC
**Please give a brief description of the data**
Heart sound recordings were sourced from several contributors around the world, collected at either a clinical or nonclinical environment, from both healthy subjects and pathological patients.

**Where can we get the data?**
Original: https://www.physionet.org/physiobank/database/challenge/2016/
Donated: The beast

**Is there a publication related to the data**
Original
@article{goldberger2000physiobank,
  title={PhysioBank, PhysioToolkit, and PhysioNet: components of a new research resource for complex physiologic signals},
  author={Goldberger, Ary L and Amaral, Luis AN and Glass, Leon and Hausdorff, Jeffrey M and Ivanov, Plamen Ch and Mark, Roger G and Mietus, Joseph E and Moody, George B and Peng, Chung-Kang and Stanley, H Eugene},
  journal={Circulation},
  volume={101},
  number={23},
  pages={e215--e220},
  year={2000},
  publisher={Am Heart Assoc}
}

**Is your data multivariate or univariate?**
Univariate

**Is there a default train/test split for the data**
No

**Are there any missing values/padding?**
No

**Is there a picture for the data we can put on the website?**
TBC

**How would you like the donation attributed on the website?**
TBC

**Can you provide a paragraph description, including the meaning of the class values, for the website?**

Heart sound recordings were sourced from several contributors around the world, collected at either a clinical or nonclinical environment, from both healthy subjects and pathological patients.
The heart sound recordings were collected from different locations on the body. The typical four locations are aortic area, pulmonic area, tricuspid area and mitral area, but could be one of nine different locations. 
The sounds were divided into two classes: normal and abnormal. The normal recordings were from healthy subjects and the abnormal ones were from patients with a confirmed cardiac diagnosis. 
The patients suffer from a variety of illnesses, but typically they are heart valve defects and coronary artery disease patients. 
Heart valve defects include mitral valve prolapse, mitral regurgitation, aortic stenosis and valvular surgery. All the recordings from the patients were generally labeled as abnormal.
Both healthy subjects and pathological patients include both children and adults.

Data was recorded at 2,000Hz.
Data was truncated to the shortest instance.

Classes:
- Normal (110)
- Abnormal (299)

Attributes: 18,530

**Comment by TonyBagnall** [comment] 2020-06-13 07:58
i this a duplicate of abnormal heartbeat?

**Comment by TonyBagnall** [comment] 2020-06-29 16:47
https://timeseriesclassification.com/description.php?Dataset=BinaryHeartbeat

**Closed by TonyBagnall** 2020-06-29 16:47 UTC
